server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/account_db?options=-c%20timezone%3DUTC
    username: bank
    password: bank
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: account-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bank.common.dto.events"

jwt:
  secret: ${JWT_SECRET:this-is-a-local-dev-secret-change-in-prod-min-32-bytes-long}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.bank: DEBUG
